version: 2
defaults: &defaults
  working_directory: ~/src
  docker:
  - image: circleci/android:api-28
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb

jobs:

  build:
    <<: *defaults

    steps:
    - attach_workspace:
        at: /home/circleci/
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
    - run:
        name: Clean Project
        command: ./gradlew clean
    - run:
        name: Build Dev Debug APK
        command: ./gradlew assembleDebug
    - persist_to_workspace:
        root: /home/circleci/
        paths:
        - src/
        destination: app/build/outputs/apk/debug/
    - store_artifacts:
        path: ~/src/app/build/outputs/apk/debug/
        destination: apk

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
